# Generated by Django 4.1.5 on 2023-02-01 12:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.CharField(default='s6KJIQ4SZBhaKM1', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contour', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('season', models.CharField(choices=[('весна', 'весна'), ('лето', 'лето'), ('осень', 'осень'), ('зима', 'зима')], default='весна', max_length=10)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.culture')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.farmer')),
            ],
        ),
    ]
